CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -Iinclude
LIBS = -lraylib -lopengl32 -lgdi32 -lwinmm

SRC = $(wildcard src/*.c)
OBJ = $(SRC:.c=.o)
TARGET = batalha_passinho.exe

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET) $(LIBS)

src/%.o: src/%.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	del /f src\*.o $(TARGET)
